version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: parking-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=MA3ERTUi
      - POSTGRES_DB=parkingdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    